In [ ]:
from sklearn import datasets
iris = datasets.load_iris()
print(iris.target_names)
print(iris.feature_names)


['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
print(iris.data[0:5])
print(iris.target)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
import pandas as pd
training_dataset = pd.DataFrame({
    'sepal length' : iris.data[:,0],
    'sepal width' : iris.data[:,1],
    'petal length' : iris.data[:,2],
    'petal width' : iris.data[:,3],
    'specious' : iris.target,
    
})
trainingdataset.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [ ]:
import os
os.getcwd()

'/content'

In [ ]:
from sklearn.model_selection import train_test_split
x = data[['sepal length', 'sepal width', 'petal length', 'petal width']]
y = data['specious']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)


In [ ]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf = RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_train, y_train)

y_pred = clf.predict(x_test) 

In [ ]:
y_pred
sepal_length = input("enter a length :")
sepal_width = input("enter a width :")
petal_length = input("enter a length :")
petal_width = input("enter a width :")
values = [sepal_length, sepal_width, petal_length,petal_width]
values

enter a length :20
enter a width :30
enter a length :40
enter a width :50


['20', '30', '40', '50']

In [ ]:
#import numpy as np
# val = np.array()

y_pred = clf.predict(sepal_length, sepal_width, petal_length, petal_width) 

NameError: ignored

In [ ]:
>>> clf = RandomForestClassifier(max_depth=2, random_state=0)
>>> clf.fit(X, y)
RandomForestClassifier(...)
>>> print(clf.predict([[0, 0, 0, 0]]))